openapi: 3.0.0
info:
  title: Microservicio de Productos
  version: 1.0.0
  description: API para gestionar productos y obtener información de productos por cliente.

servers:
  - url: http://localhost:8082
    description: Entorno local

paths:
  /products/active:
    get:
      summary: Obtener productos activos
      description: Devuelve una lista de todos los productos activos.
      responses:
        200:
          description: Lista de productos activos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
        500:
          description: Error interno del servidor

  /products/{productId}:
    get:
      summary: Obtener producto por ID
      description: Devuelve detalles de un producto específico por su ID.
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Detalles del producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        404:
          description: Producto no encontrado
        500:
          description: Error interno del servidor
    patch:
      summary: Actualizar parcialmente un producto por ID
      description: Actualiza campos específicos de un producto por su ID.
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductPatchRequest'
      responses:
        200:
          description: Producto actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        404:
          description: Producto no encontrado
        400:
          description: Solicitud incorrecta
        500:
          description: Error interno del servidor

    put:
      summary: Actualizar producto por ID
      description: Actualiza un producto por su ID.
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdateRequest'
      responses:
        200:
          description: Producto actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        404:
          description: Producto no encontrado
        400:
          description: Solicitud incorrecta
        500:
          description: Error interno del servidor

    delete:
      summary: Eliminar producto por ID
      description: Elimina un producto por su ID.
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Producto eliminado con éxito
        404:
          description: Producto no encontrado
        500:
          description: Error interno del servidor

  /products:
    post:
      summary: Insertar un nuevo producto
      description: Inserta un producto en la base de datos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateRequest'
      responses:
        201:
          description: Producto creado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        400:
          description: Solicitud incorrecta
        500:
          description: Error interno del servidor

  /products/customer/{customerId}:
    get:
      summary: Obtener productos activos de un cliente
      description: Devuelve una lista de productos asociados con un cliente específico, con la opción de filtrar por estado.
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          description: ID del cliente
        - name: state
          in: query
          required: false
          schema:
            type: string
          description: Estado del producto para filtrar (por ejemplo, "ACTIVE", "INACTIVE")
      responses:
        200:
          description: Lista de productos para el cliente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
        404:
          description: Cliente o productos no encontrados
        500:
          description: Error interno del servidor

components:
  schemas:
    ProductResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        document_number:
          type: string
        state:
          type: string

    ProductCreateRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        document_number:
          type: string
        state:
          type: string

    ProductUpdateRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        document_number:
          type: string
        state:
          type: string
    ProductPatchRequest:
      type: object
      description: Campos que pueden ser actualizados en un producto
      properties:
        name:
          type: string
        description:
          type: string
        document_number:
          type: string
        state:
          type: string
      required: [ ]
